name: Rest API integration check and deployment

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./rest_api

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-pip

      - name: Clone Yolov5
        run: git clone https://github.com/ultralytics/yolov5.git

      - name: Install face_recognition
        run: |
          git clone -b 'v19.9' --single-branch https://github.com/davisking/dlib.git dlib/
          cd dlib
          python3 setup.py install --yes USE_AVX_INSTRUCTIONS
        
      - name: Install other Python packages from requirements.txt
        run: pip install -r requirements.txt

      - name: Deploy flask API server
        run: python api.py

      - name: Run test.py script
        run: python test.py
